INSERT INTO INGRESSO (ID_INGRESSO,TIPO,VALOR) VALUES (1,'VIP',1000);
INSERT INTO INGRESSO (ID_INGRESSO,TIPO,VALOR) VALUES (2,'BACKSTAGE',800);
INSERT INTO INGRESSO (ID_INGRESSO,TIPO,VALOR) VALUES (3,'PLATEIA VIP',500);
INSERT INTO INGRESSO (ID_INGRESSO,TIPO,VALOR) VALUES (4,'PLATEIA',300);